"""
en/discovery + en/lib_new 영문 자동 번역
- 광범위 어휘 사전 일괄 치환
- KaTeX/HTML 태그/<a>/<script> 보존
- 매 카드 CLI 출력
"""
import glob, re, os

# ─────────── 광범위 한영 사전 ───────────
DICT = {
    # 핵심 박스/섹션 (이미 영문화된 것 포함, 안전망)
    '핵심 발견': 'Core Finding',
    '왜 이 판정인가': 'Why This Verdict',
    'v1.8 공리 기준 5단계 재귀 대입': '5-Step Recursive Substitution (v1.8 Axiom Base)',
    'v1.8 카테고리 정정': 'v1.8 Category Correction',
    '부산물': 'Byproducts',
    '미완': 'Incomplete',
    '총괄': 'Summary',
    'D 승급 (Hypothesis → Discovery)': 'D Promotion (Hypothesis → Discovery)',
    '승급 사유': 'Promotion Rationale',
    '가설에서 멈춘 이유': 'Why the Hypothesis Halted',

    # 5단계 절차
    '1단계. 반야식 출발': 'Step 1. Banya Formula',
    '2단계. 노름 치환': 'Step 2. Norm Substitution',
    '3단계. 상수 + 가설 재투입': 'Step 3. Constant + Hypothesis Re-injection',
    '3단계. 상수 + 가설 재투입 (재귀 대입)': 'Step 3. Constant + Hypothesis Re-injection',
    '4단계. 도메인 변환': 'Step 4. Domain Transformation',
    '5단계. 발견 / 판정': 'Step 5. Discovery / Verdict',
    'delta가 대상 도메인으로': 'δ to target domain',
    '모든 채굴은 이 1줄에서 시작': 'All mining starts from this single line',
    'CAS 단일 연산자 + 4축 직교': 'CAS sole operator + 4-axis orthogonality',
    '위 본문의 식이 도메인 변환의 결과': 'The formula above is the result of domain transformation',
    'v1.8 어휘 정렬': 'v1.8 terminology alignment',
    '직교 합성': 'orthogonal composition',
    '직교 부분공간': 'orthogonal subspace',
    '직교 경계 순서 강제 횡단': 'orthogonal boundary ordered crossing',
    '좌우항 동일 변화량 선언': 'declaration of equal change on both sides',
    '괄호 내': 'within bracket',
    'delta 발화비트': 'δ utterance bit',
    '발화비트': 'utterance bit',

    # 판정
    '판정 변경: 가설 → 발견': 'Verdict Change: Hypothesis → Discovery',
    '판정: 발견': 'Verdict: Discovery',
    '판정: 가설': 'Verdict: Hypothesis',
    '판정: 예측': 'Verdict: Prediction',
    '판정: 적중': 'Verdict: Hit',
    '판정:': 'Verdict:',
    '발견</span>': 'Discovery</span>',
    '가설</span>': 'Hypothesis</span>',
    '예측</span>': 'Prediction</span>',
    '적중</span>': 'Hit</span>',
    '재귀 대입 진행 중': 'recursive substitution in progress',
    '실험 검증 대기': 'awaiting experimental verification',
    '분류 I (공리 도출, forward chain 완료)': 'Class I (axiom derivation, forward chain complete)',
    '분류 II': 'Class II',
    '분류 III (공리 내적 서술)': 'Class III (axiom-internal narrative)',
    '분류 III': 'Class III',
    '분류 IV': 'Class IV',

    # 조건/이유
    '명시적 도출 식 존재': 'explicit derivation formula exists',
    '실험 비교 오차': 'experimental comparison error',
    '재귀 대입 입력': 'recursive substitution inputs',
    'forward chain 완료': 'forward chain complete',
    '잔여 과제 명시': 'remaining tasks specified',
    '자유 매개변수 0개': '0 free parameters',
    '충족 조건:': 'Conditions Met:',
    '공리 인용': 'axioms cited',
    '도출 식 존재': 'derivation formula exists',

    # 위치/카테고리
    '카테고리:': 'Category:',
    '도메인:': 'Domain:',
    '재귀 대입 경로:': 'Recursive substitution path:',
    '이유:': 'Reason:',
    '위치:': 'Location:',
    '관련 공리:': 'Related Axioms:',

    # 입력
    '1차 정수 (': 'Primary Integers (',
    '물리 상수 입력:': 'Physical Constant Inputs:',
    '입력 상수 없음': 'no input constant',
    '라이브러리 재투입:': 'Library Re-substitution:',
    '재대입 용도:': 'Re-substitution Purpose:',

    # 표 헤더
    '항목': 'Item',
    '현재 상태': 'Current State',
    '해결 방향': 'Solution Direction',
    '결과': 'Result',
    '상태': 'Status',

    # 미완 표
    '구조 서술까지': 'Structure narrative only',
    '재귀 대입 다음 라운드': 'Next-round recursive substitution',
    '실험 검증': 'Experimental verification',
    '이론값 산출': 'Theoretical value derivation',
    '판정 미정': 'Verdict pending',
    '미정': 'pending',
    '2-loop 이상 보정': '2-loop and higher corrections',
    '1-loop 수준': '1-loop level',
    '반야프레임 재귀 대입 정밀화': 'Banya Framework recursive refinement',
    '구조 서술 완료, 정량 산출 보류': 'structural narrative complete, quantitative derivation pending',

    # v1.8 정정 박스
    '주의:': 'Note:',
    '지적:': 'Issue:',
    'v1.8 정정:': 'v1.8 Correction:',
    '핵심 정정 1': 'Key Correction 1',
    '핵심 정정 2': 'Key Correction 2',
    '유지되는 부분:': 'Retained parts:',
    'v1.8 재채굴 식:': 'v1.8 Re-mined Formula:',
    '4력 v1.8 분류 (physics_map):': '4 Forces v1.8 (physics_map):',
    '4력 v1.8 분류': '4 Forces v1.8',
    'physics_map.html v1.8 4력 분류': 'physics_map.html v1.8 4-force classification',
    '강력=FSM 원자성': 'strong=FSM atomicity',
    '약력=수축 겹침·직렬화': 'weak=contraction overlap·serialization',
    '전자기=교차 Cmp/Swp 비용': 'EM=cross Cmp/Swp cost',
    '중력=√3 노름 누적·쥠 밀집 수축': 'gravity=√3 norm accumulation·juim density contraction',
    'ring 없음, 비용 아닌 기하 수축': 'no ring, geometric not cost',
    '본 카드 라이브러리 본문은 v1.0~1.2 시기 채굴이며': 'The library body of this card is v1.0~1.2 mining and',
    'v1.8 공리/physics_map와 일부 불일치': 'partially inconsistent with v1.8 axioms/physics_map',

    # 4력
    '강력': 'strong force',
    '약력': 'weak force',
    '전자기력': 'electromagnetic force',
    '중력': 'gravity',
    '4력 통합': '4-force unification',

    # CAS / 공리 핵심 어휘
    '비용': 'cost',
    '비용 누적': 'cost accumulation',
    '비용 회수': 'cost recovery',
    '비가역': 'irreversible',
    '가역': 'reversible',
    '직교': 'orthogonal',
    '직교성': 'orthogonality',
    '원자성': 'atomicity',
    '관측자': 'observer',
    '중첩': 'superposition',
    '발화': 'utterance',
    '폴링': 'polling',
    '쥠': 'juim',
    '쥐기': 'juigi',
    '쥐다': 'juida',
    '워크벤치': 'workbench',
    '자료형': 'data type',
    '도메인': 'domain',
    '구조': 'structure',
    '구조적': 'structural',
    '기하학적': 'geometric',
    '연속': 'continuous',
    '이산': 'discrete',
    '닫힌': 'closed',
    '열린': 'open',
    '횡단': 'crossing',
    '경계': 'boundary',
    '경합': 'contention',
    '직렬화': 'serialization',
    '인덱싱': 'indexing',
    '필터': 'filter',
    '진입점': 'entry point',
    '주소 없는': 'addressless',
    '논리주소': 'logical address',
    '회로': 'circuit',
    '단일 연산자': 'sole operator',
    '유일한 연산자': 'sole operator',
    '시간 밖': 'outside time',
    '시스템 시간': 'system time',
    '도메인 시간': 'domain time',
    '발화 주기': 'utterance period',
    '비용 보존': 'cost conservation',
    '전체-국소 루프': 'whole-local loop',
    '자기참조': 'self-reference',
    '다중 투영': 'multiple projection',
    '인과율': 'causality',
    '인과율 보존': 'causality preservation',
    '레지스터': 'register',
    '엔티티': 'entity',
    '엔티티 간 거리': 'inter-entity distance',
    '상호작용 세기': 'interaction strength',
    '수축 영역': 'contraction region',
    '수축 겹침': 'contraction overlap',
    '겹침비': 'overlap ratio',
    '읽기 경합': 'read contention',
    '시공간 곡률': 'spacetime curvature',
    '시공간': 'spacetime',
    '곡률': 'curvature',
    '의식': 'consciousness',
    '덕 타입': 'duck type',
    '괄호': 'bracket',
    '양자 괄호': 'quantum bracket',
    '고전 괄호': 'classical bracket',
    '입자': 'particle',
    '광자': 'photon',
    '글루온': 'gluon',
    '중력자': 'graviton',
    '쿼크': 'quark',
    '렙톤': 'lepton',
    '뮤온': 'muon',
    '타우': 'tau',
    '전자': 'electron',
    '뉴트리노': 'neutrino',
    '힉스': 'Higgs',
    '보손': 'boson',
    '게이지 보손': 'gauge boson',
    '바리온': 'baryon',
    '메손': 'meson',
    '하드론': 'hadron',
    '파이온': 'pion',
    '색 자유도': 'color degree of freedom',
    '색 가둠': 'color confinement',
    '점근적 자유': 'asymptotic freedom',
    '대칭': 'symmetry',
    '대칭 깨짐': 'symmetry breaking',
    '게이지': 'gauge',
    '게이지 군': 'gauge group',
    '통일': 'unification',
    '대통일': 'grand unification',
    '결합상수': 'coupling constant',
    '결합': 'coupling',
    '미세구조상수': 'fine-structure constant',
    '바인베르크 각': 'Weinberg angle',
    '강결합상수': 'strong coupling constant',
    '카비보 각': 'Cabibbo angle',
    '혼합각': 'mixing angle',
    '암흑물질': 'dark matter',
    '암흑에너지': 'dark energy',
    '우주상수': 'cosmological constant',
    '바리온-광자 비': 'baryon-to-photon ratio',
    '플랑크 시간': 'Planck time',
    '플랑크 길이': 'Planck length',
    '플랑크 질량': 'Planck mass',
    '슈바르츠실트': 'Schwarzschild',
    '사건지평': 'event horizon',
    '블랙홀': 'black hole',
    '진공': 'vacuum',
    '진공 편극': 'vacuum polarization',
    '진공 에너지': 'vacuum energy',
    '얽힘': 'entanglement',
    '비국소성': 'nonlocality',
    '특이점': 'singularity',
    '특이점 부재': 'no singularity',
    '양자화': 'quantization',
    '코이데': 'Koide',
    '코이데 공식': 'Koide formula',
    'PMNS 태양 혼합각': 'PMNS solar mixing angle',
    'PMNS 대기 혼합각': 'PMNS atmospheric mixing angle',
    'PMNS 반응로 혼합각': 'PMNS reactor mixing angle',
    '뉴트리노 질량': 'neutrino mass',
    '뉴트리노 질량합': 'neutrino mass sum',
    '4세대 부재': '4th generation absence',
    '양성자 수명': 'proton lifetime',
    '시간 팽창': 'time dilation',
    '쌍둥이 역설': 'twin paradox',
    '등가 원리': 'equivalence principle',
    '관성': 'inertia',
    '관성질량': 'inertial mass',
    '중력질량': 'gravitational mass',
    '질량': 'mass',
    '질량비': 'mass ratio',
    '질량 계층': 'mass hierarchy',
    '질량 차이': 'mass difference',
    '톱 쿼크': 'top quark',
    '참 쿼크': 'charm quark',
    '업 쿼크': 'up quark',
    '다운 쿼크': 'down quark',
    '스트레인지 쿼크': 'strange quark',
    '보텀 쿼크': 'bottom quark',
    '바리오제네시스': 'baryogenesis',

    # 일반 어구
    '발견': 'discovery',
    '가설': 'hypothesis',
    '예측': 'prediction',
    '적중': 'hit',
    '식': 'formula',
    '도출': 'derivation',
    '도출했다': 'derived',
    '도출한다': 'derives',
    '유도': 'induction',
    '치환': 'substitution',
    '대입': 'substitution',
    '재투입': 're-injection',
    '재대입': 're-substitution',
    '재귀 대입': 'recursive substitution',
    '재귀': 'recursive',
    '오차': 'error',
    '실험값': 'experimental value',
    '실험': 'experiment',
    '측정': 'measurement',
    '측정값': 'measured value',
    '교차 검증': 'cross-verification',
    '검증': 'verification',
    '검증/반박': 'verification/refutation',
    '반박': 'refutation',
    '비교': 'comparison',
    '정확': 'exact',
    '정확 일치': 'exact match',
    '구조적 대응': 'structural correspondence',
    '구조적 필연': 'structural necessity',
    '구조적 식별': 'structural identification',
    '필연': 'necessity',
    '자연 도출': 'natural derivation',
    '자동 도출': 'automatic derivation',
    '강제': 'forces',
    '강제된다': 'is forced',
    '강제한다': 'forces',
    '확정': 'determined',
    '확정된다': 'is determined',
    '결정': 'determined',
    '결정된다': 'is determined',
    '대응': 'correspondence',
    '대응한다': 'corresponds to',
    '동일': 'identical',
    '같은': 'same',
    '다른': 'different',
    '동형': 'isomorphism',
    '동형성': 'isomorphism',
    '일치': 'matches',
    '일치한다': 'matches',
    '재현': 'reproduction',
    '재현된다': 'is reproduced',
    '항등식': 'identity',
    '카테고리': 'category',
    '카테고리 오류': 'category error',
    '잔존': 'remaining',
    '잔여': 'residual',
    '잔존 비용': 'residual cost',
    '공값': 'ball-value',
    '공': 'ball',
    '공 1개': '1 ball',
    '쥠의 비용': 'cost of juim',
    '쥠 밀집 수축': 'juim density contraction',
    '노름 누적': 'norm accumulation',
    '노름': 'norm',
    '단위': 'unit',
    '최소비용': 'minimum cost',
    '최소작용': 'least action',
    '닫힌 회로': 'closed circuit',
    '열린 ECS': 'open ECS',
    '열린': 'open',
    '거리 무관': 'distance-independent',
    '동시': 'simultaneous',
    '평행': 'parallel',
    '독립': 'independent',
    '독립적': 'independent',
    '병렬': 'parallel',
    '병렬 실행': 'parallel execution',
    '무한': 'infinite',
    '유한': 'finite',
    '근사': 'approximation',
    '극한': 'limit',
    '저에너지 극한': 'low-energy limit',
    '고에너지 한계': 'high-energy limit',
    '점근': 'asymptotic',
    '운영': 'operation',
    '연산': 'operation',
    '연산자': 'operator',
    '단계': 'stage',
    '단일 연산': 'single operation',
    '불가분 연산': 'atomic operation',
    '비트': 'bit',
    '8비트': '8-bit',
    '7비트': '7-bit',
    '4비트': '4-bit',
    '3비트': '3-bit',
    '니블': 'nibble',
    '니블 0': 'nibble 0',
    '니블 1': 'nibble 1',
    '링': 'ring',
    '링 버퍼': 'ring buffer',
    '링 이음새': 'ring seam',
    '순서': 'order',
    '순서 강제': 'order enforcement',
    '순환': 'cyclic',
    '주기적': 'periodic',
    '주기': 'period',
    '시점': 'moment',
    '발화 시점': 'utterance moment',
    '비교': 'compare',
    '판정': 'verdict',
    '확률': 'probability',
    '진폭': 'amplitude',
    '확률 진폭': 'probability amplitude',
    '관측 트리거': 'observation trigger',
    '관측 효과': 'observation effect',
    '관측 문제': 'measurement problem',
    '관측': 'observation',

    # 메타 표현
    '본 카드는': 'This card is',
    '본 카드': 'This card',
    '본 가설은': 'This hypothesis',
    '본 가설': 'This hypothesis',
    '본 발견은': 'This discovery',
    '본 발견': 'This discovery',
    '본 도출은': 'This derivation',
    '본 도출': 'This derivation',
    '본 라운드': 'This round',
    '다음 라운드': 'Next round',
    '이전 라운드': 'Previous round',
    '후속': 'subsequent',
    '후속 작업': 'subsequent work',
    '후속 라운드': 'subsequent round',
    '후속 라운드 과제': 'subsequent round task',
    '잔여 과제': 'remaining task',
    '미완 항목': 'incomplete item',
    '미해결': 'unsolved',
    '미해결 문제': 'unsolved problem',

    # 자주 등장하는 동사
    '있다': 'exists',
    '없다': 'does not exist',
    '한다': 'do',
    '된다': 'becomes',
    '나타난다': 'appears',
    '나타나며': 'appears, and',
    '드러난다': 'is revealed',
    '의미한다': 'means',
    '뜻한다': 'means',
    '확인한다': 'confirms',
    '확인된다': 'is confirmed',
    '제공한다': 'provides',
    '입증한다': 'proves',
    '입증된다': 'is proven',
    '시사한다': 'suggests',
    '예측한다': 'predicts',
    '예측된다': 'is predicted',
    '설명한다': 'explains',
    '설명된다': 'is explained',
    '재해석한다': 'reinterprets',
    '재해석된다': 'is reinterpreted',
    '분류된다': 'is classified',
    '분류한다': 'classifies',
    '포함한다': 'includes',
    '포함된다': 'is included',
    '구성한다': 'constitutes',
    '구성된다': 'is constituted by',

    # 자주 등장하는 연결어
    '따라서': 'Therefore',
    '그러므로': 'Therefore',
    '즉': 'i.e.',
    '예를 들어': 'For example',
    '특히': 'In particular',
    '다만': 'However',
    '하지만': 'However',
    '그러나': 'However',
    '또한': 'Also',
    '게다가': 'Moreover',
    '한편': 'On the other hand',
    '반면': 'In contrast',
    '결국': 'Eventually',
    '결과적으로': 'As a result',
    '비교하면': 'Compared to',
    '예: ': 'e.g.,',
    '주: ': 'Note: ',
    '잔존': 'residual',

    # 단위
    '오차 0%': 'Error 0%',
    '구조적 대응': 'structural correspondence',
    '정수 정확': 'integer exact',
    '정수 일치': 'integer match',
    '자릿수 정확': 'digits exact',
    '자릿수 일치': 'digits match',

    # 등급
    'S급': 'S-grade',
    'A급': 'A-grade',
    'B급': 'B-grade',
    'C급': 'C-grade',

    # 푸터/라이센스 (이미 처리됨, 안전망)
    '반야프레임 (般若 Framework)': 'Banya Framework (般若)',
    '발명자: 한혁진 (Han Hyukjin)': 'Inventor: Han Hyukjin',
    '이메일:': 'Email:',
    '별칭: 부처님 손바닥 프레임': 'Alias: Buddha\'s Palm Framework',
    '분류: 공리 기반 과학 채굴 엔진 (Axiom-Based Science Mining Engine)':
        'Classification: Axiom-Based Science Mining Engine',
    '반야프레임': 'Banya Framework',
    '공리 기반 과학 채굴 엔진': 'Axiom-Based Science Mining Engine',

    # 자주 보이는 짧은 단어 (마지막에 배치, 긴 매칭 우선)
    '입력': 'input',
    '출력': 'output',
    '시작': 'start',
    '끝': 'end',
    '경로': 'path',
    '경로의': 'path\'s',
    '체인': 'chain',
    '사슬': 'chain',
    '사이클': 'cycle',
    '플래그': 'flag',
    '전역': 'global',
    '국소': 'local',
    '전역 플래그': 'global flag',
    '국소 상태': 'local state',
    '닫힘': 'closure',
    '본문': 'body',
    '본문에': 'in the body',
    '본문은': 'the body is',
    '본문의': 'of the body',
    '라이브러리': 'library',
    '라이브러리 본문': 'library body',
    '라이브러리에': 'in the library',
    '재투입': 're-injection',
    '재대입': 're-substitution',

    # 한국어 어미들 (가장 마지막에 배치)
}

# 사전 정렬 — 긴 키 먼저 매칭
SORTED = sorted(DICT.items(), key=lambda x: -len(x[0]))

def translate(html):
    """KaTeX/HTML/스크립트 보존 후 사전 일괄 치환"""
    placeholders = {}
    pid = [0]
    def stash(m):
        key = '\x00T' + str(pid[0]) + '\x00'
        placeholders[key] = m.group(0)
        pid[0] += 1
        return key
    # 보호
    html = re.sub(r'<script[^>]*>.*?</script>', stash, html, flags=re.S)
    html = re.sub(r'<style[^>]*>.*?</style>', stash, html, flags=re.S)
    html = re.sub(r'<a\b[^>]*>.*?</a>', stash, html, flags=re.S)
    html = re.sub(r'\$\$.*?\$\$', stash, html, flags=re.S)
    html = re.sub(r'\$[^$]+\$', stash, html, flags=re.S)
    # HTML 태그 보호 (속성 안 한국어 보존)
    html = re.sub(r'<[a-zA-Z][^>]*>', stash, html)

    # 사전 치환
    for ko, en in SORTED:
        html = html.replace(ko, en)

    # 복원
    for k, v in placeholders.items():
        html = html.replace(k, v)
    return html

# 실행
files = sorted(glob.glob('en/discovery/[dhp][0-9]*.html'))
total = len(files)
done = 0
for f in files:
    with open(f, 'r', encoding='utf-8') as fp: c = fp.read()
    new = translate(c)
    if new != c:
        with open(f, 'w', encoding='utf-8') as fp: fp.write(new)
        done += 1
    print(f"[{done:4d}/{total}] {os.path.basename(f)}", flush=True)

# lib_new도
with open('en/lib_new.html', 'r', encoding='utf-8') as fp: c = fp.read()
new = translate(c)
if new != c:
    with open('en/lib_new.html', 'w', encoding='utf-8') as fp: fp.write(new)
    print("en/lib_new.html 번역")

print(f"\n=== 자동 번역 완료: {done}/{total} ===")
